export const ENV_VARS = {
  PORT: 'PORT',
  MONGODB_USER: 'MONGODB_USER',
  MONGODB_PASSWORD: 'MONGODB_PASSWORD',
  MONGODB_URL: 'MONGODB_URL',
  MONGODB_DB: 'MONGODB_DB',
};

export const FIFTEEN_MINUTES = 1000 * 60 * 15; //15 min
export const ONE_DAY = 1000 * 60 * 60 * 24; //24 hour
